# **4 TO - DO - Task**

# **4.1 Exercise on Functions:**

Task - 1:

Create a Python program that converts between different units of measurement.

In [ ]:
def convert_units():
    """
    Convert units for length, weight or volume
    """

    print("Enter conversion type:")
    print("1 = Length")
    print("2 = Weight")
    print("3 = Volume")

    choice = input("Enter your choice: ")

    try:
        value = float(input("Enter a value to convert: "))

        if choice == "1":
            print("1 = meters to feet")
            print("2 = feet to meters")
            option = input("Choose an option: ")

            if option == "1":
                result = value * 3.28084
                print("Result:", result, "feet")

            elif option == "2":
                result = value / 3.28084
                print("Result:", result, "meters")

        elif choice == "2":
            print("1 = kg to pounds")
            print("2 = pounds to kg")
            option = input("Choose an option: ")

            if option == "1":
                result = value * 2.20462
                print("Result:", result, "pounds")

            elif option == "2":
                result = value / 2.20462
                print("Result:", result, "kg")

        elif choice == "3":
            print("1 = liters to gallons")
            print("2 = gallons to liters")
            option = input("Choose an option: ")

            if option == "1":
                result = value * 0.264172
                print("Result:", result, "gallons")

            elif option == "2":
                result = value / 0.264172
                print("Result:", result, "liters")

        else:
            print("Wrong choice")

    except:
        print("Please enter a valid number")

convert_units()

Enter conversion type:
1 = Length
2 = Weight
3 = Volume
Enter your choice: 3
Enter a value to convert: 12
1 = liters to gallons
2 = gallons to liters
Choose an option: 2
Result: 45.4249504110958 liters


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

In [4]:
def find_sum(numbers):
    """Return sum of numbers"""
    total = 0
    for n in numbers:
        total = total + n
    return total


def find_avg(numbers):
    """Return average"""
    total = find_sum(numbers)
    avg = total / len(numbers)
    return avg


def find_max(numbers):
    """Return maximum value"""
    maximum = numbers[0]
    for n in numbers:
        if n > maximum:
            maximum = n
    return maximum


def find_min(numbers):
    """Return minimum value"""
    minimum = numbers[0]
    for n in numbers:
        if n < minimum:
            minimum = n
    return minimum


try:
  user_input = input("Enter numbers separated by space: ")
  numbers = []

  for n in user_input.split():
    numbers.append(float(n))

  print("Choose the operation to perform:")
  print("1 = Sum")
  print("2 = Average")
  print("3 = Maximum")
  print("4 = Minimum")

  choice  = int(input("Enter your choice: "))

  if choice == 1:
    print(find_sum(numbers))

  elif choice == 2:
    print(find_avg(numbers))

  elif choice == 3:
    print(find_max(numbers))

  elif choice == 4:
    print(find_min(numbers))

  else:
    print("Invalid choice")

except:
    print("Invalid input")

Enter numbers separated by space: 2 4 3 1
Choose the operation to perform:
1 = Sum
2 = Average
3 = Maximum
4 = Minimum
Enter your choice: 3
4.0


# **4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

In [5]:
def extract_every_other(lst):
    result = []
    for i in range(0, len(lst), 2):
        result.append(lst[i])
    return result

2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [9]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing

In [17]:
def reverse_list(lst):
    return lst[::-1]

4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [11]:
def remove_first_last(lst):
    return lst[1:-1]

5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

In [12]:
def get_first_n(lst, n):
    return lst[:n]

6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

In [13]:
def get_last_n(lst, n):
    return lst[-n:]

7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [14]:
def reverse_skip(lst):
    return lst[-2::-2]

**Test Cases**

In [31]:
test_list = [41, 52, 36, 14, 92, 18]

print("Extract Every Other Element:", extract_every_other(test_list))
print("Slice a Sublist:", get_sublist(test_list, 1, 3))
print("Reverse a List Using Slicing:", reverse_list(test_list))
print("Remove the First and Last Elements:", remove_first_last(test_list))
print("Get the First n Elements:", get_first_n(test_list, 3))
print("Extract Elements from the End:", get_last_n(test_list, 3))
print("Extract Elements in Reverse Order:", reverse_skip(test_list))

Extract Every Other Element: [41, 36, 92]
Slice a Sublist: [52, 36, 14]
Reverse a List Using Slicing: [18, 92, 14, 36, 52, 41]
Remove the First and Last Elements: [52, 36, 14, 92]
Get the First n Elements: [41, 52, 36]
Extract Elements from the End: [14, 92, 18]
Extract Elements in Reverse Order: [92, 36, 41]


# **4.3 Exercise on Nested List:**

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [23]:
def flatten(lst):
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

In [24]:
def access_nested_element(lst, indices):
    element = lst

    for i in indices:
        element = element[i]

    return element

3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).


In [25]:
def sum_nested(lst):
    total = 0

    for item in lst:
        if type(item) == list:
            total = total + sum_nested(item)
        else:
            total = total + item

    return total

4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

In [26]:
def remove_element(lst, elem):
    result = []

    for item in lst:
        if type(item) == list:
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result

5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [50]:
def find_max(lst):
    max_val = None

    for item in lst:
        if type(item) == list:
            value = find_max(item)
        else:
            value = item

        if max_val is None or value > max_val:
            max_val = value

    return max_val

6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

In [28]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if type(item) == list:
            count = count + count_occurrences(item, elem)
        elif item == elem:
            count = count + 1

    return count

7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [29]:
def deep_flatten(lst):
    result = []

    for item in lst:
        if type(item) == list:
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth

In [30]:
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

**Test Cases**

In [51]:
nested_list = [[1,2],[3,[4,5]],6]

print("Flatten:", flatten([[1,2],[3,4],[5]]))
print("Access Nested Element:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))
print("Sum Nested:", sum_nested(nested_list))
print("Remove Element:", remove_element([[1,2],[3,2],[4,5]], 2))
print("Find Max:", find_max(nested_list))
print("Count Occurrences:", count_occurrences([[1,2],[2,3],[2,4]], 2))
print("Deep Flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))
print("Average Nested:", average_nested([[1,2],[3,4],[5,6]]))

Flatten: [1, 2, 3, 4, 5]
Access Nested Element: 6
Sum Nested: 21
Remove Element: [[1], [3], [4, 5]]
Find Max: 6
Count Occurrences: 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average Nested: 3.5


# **10 To - Do - NumPy**

In [1]:
import numpy as np

# **10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

In [6]:
# 1 Initialize empty array 2x2
a = np.empty((2,2))
print("Empty array:\n", a)

# 2 All ones array 4x2
b = np.ones((4,2))
print("Ones array:\n", b)

# 3 Array filled with a value
c = np.full((3,3), 7)
print("Full array:\n", c)

# 4 Zeros like existing array
d = np.zeros_like(c)
print("Zeros like c:\n", d)

# 5 Ones like existing array
e = np.ones_like(c)
print("Ones like c:\n", e)

# 6 Convert list to numpy array
new_list = [1, 2, 3, 4]
f = np.array(new_list)
print("Array from list:", f)

Empty array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like c:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Ones like c:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Array from list: [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

In [7]:
# 1 Values from 10 to 49
a = np.arange(10,50)
print("10 to 49:\n", a)

# 2 Create 3x3 matrix from 0 to 8
b = np.arange(9).reshape(3,3)
print("3x3 matrix:\n", b)

# 3 Identity matrix
c = np.eye(3)
print("Identity matrix:\n", c)

# 4 Random array
d = np.random.rand(3,3)
print("Random array:\n", d)

10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
 [[0.9287619  0.35883999 0.90967365]
 [0.54281336 0.91881754 0.71343804]
 [0.09181355 0.84449314 0.3395736 ]]


**Problem - 3: Array Operations:**

In [35]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Add the two array
print("Add:\n", x + y)

# 2 Subtract the two array
print("Subtract:\n", x - y)

# 3 Multiply the array with any integers of your choice
print("Multiply by 2:\n", x * 2)

# 4 Find the square of each element of the array
print("Square of x:\n", x**2)

# 5 Find the dot product between: v(and)w ; x(and)v ; x(and)y
print("v dot w:", np.dot(v,w))
print("x dot v:", np.dot(x,v))
print("x dot y:\n", np.dot(x,y))

# 6 Concatenate x(and)y along row and Concatenate v(and)w along column
# concatenate x and y along rows
print("Concatenate rows:\n", np.vstack((x,y)))
# concatenate v and w as columns
print("Concatenate columns:\n", np.column_stack((v,w)))

# 7 Concatenate x(and)v.
try:
    print(np.concatenate((x,v)))
except:
    print("Error: dimensions do not match")

Add:
 [[ 6  8]
 [10 13]]
Subtract:
 [[-4 -4]
 [-4 -3]]
Multiply by 2:
 [[ 2  4]
 [ 6 10]]
Square of x:
 [[ 1  4]
 [ 9 25]]
v dot w: 219
x dot v: [29 77]
x dot y:
 [[19 22]
 [50 58]]
Concatenate rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate columns:
 [[ 9 11]
 [10 12]]
Error: dimensions do not match


**Explanation:** The above error occured because the dimension of x is 2D array whereas the dimension of v is 1D array so Numpy cannot perform the operation of concatination on the arrays with different dimensions.

**Problem - 4: Matrix Operations:**

For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

In [13]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

1. Prove A.A−1 = I.

In [14]:
A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A * A inverse:\n", result)

A * A inverse:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [15]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


3. Prove (AB)ᵀ = Bᵀ Aᵀ.

In [16]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [33]:
import numpy as np

A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution using inverse method:", X)

Solution using inverse method: [ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function. {Explore more about ”linalg” function of Numpy}

In [34]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

solution = np.linalg.inv(A).dot(B)

print("Solution using np.linalg.inv:", solution)

Solution using np.linalg.inv: [ 2.  1. -2.]


# **10.2 Experiment: How Fast is Numpy?**

**1. Element-wise Addition:**

In [25]:
import time

size = 1000000

# python lists
a = list(range(size))
b = list(range(size))

start = time.time()

result = []
for i in range(size):
    result.append(a[i] + b[i])

end = time.time()

print("Python addition time:", end-start)

Python addition time: 0.1612234115600586


In [26]:
# NumPy version

a = np.arange(size)
b = np.arange(size)

start = time.time()

result = a + b

end = time.time()

print("NumPy addition time:", end-start)

NumPy addition time: 0.02529311180114746


**2. Element-wise Multiplication:**

In [27]:
import time

size = 1000000

# python lists
a = list(range(size))
b = list(range(size))

start = time.time()

result = []
for i in range(size):
    result.append(a[i] * b[i])

end = time.time()

print("Python multiplication time:", end-start)

Python multiplication time: 0.16777586936950684


In [28]:
# NumPy version

a = np.arange(size)
b = np.arange(size)

start = time.time()

result = a * b

end = time.time()

print("NumPy multiplication time:", end-start)

NumPy multiplication time: 0.013632535934448242


**3. Dot Product**

In [29]:
import time

size = 1000000

a = list(range(size))
b = list(range(size))

start = time.time()

dot = 0
for i in range(size):
    dot = dot + a[i] * b[i]

end = time.time()

print("Python dot product:", dot)
print("Python time:", end - start)

Python dot product: 333332833333500000
Python time: 0.43083906173706055


In [30]:
import numpy as np
import time

size = 1000000

a = np.arange(size)
b = np.arange(size)

start = time.time()

dot = np.dot(a,b)

end = time.time()

print("NumPy dot product:", dot)
print("NumPy time:", end - start)

NumPy dot product: 333332833333500000
NumPy time: 0.0017199516296386719


**4. Matrix Multiplication**

In [31]:
import time

A = [[1,2],[3,4]]
B = [[5,6],[7,8]]

start = time.time()

result = [[0,0],[0,0]]

for i in range(2):
    for j in range(2):
        for k in range(2):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Python matrix multiplication:", result)
print("Python time:", end - start)

Python matrix multiplication: [[19, 22], [43, 50]]
Python time: 0.00016951560974121094


In [32]:
import numpy as np
import time

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy matrix multiplication:\n", result)
print("NumPy time:", end - start)

NumPy matrix multiplication:
 [[19 22]
 [43 50]]
NumPy time: 0.00010609626770019531
